module.exports.rules = {
  'arrow-return-shorthand': true,
  'await-promise': true,
  'binary-expression-operand-order': true,
  'callable-types': true,
  'class-name': true,
  'comment-format': [true, 'check-space'],
  'curly': true,
  'cyclomatic-complexity': true,
  'deprecation': {
    severity: 'warn',
  },
  'encoding': true,
  'forin': true,
  'import-blacklist': [true, 'rxjs/Rx'],
  'interface-name': [true, 'never-prefix'],
  'interface-over-type-literal': true,
  'jsdoc-format': [true, 'check-multiline-start'],
  'label-position': true,
  'match-default-export-name': false,
  'max-classes-per-file': [true, 1],
  'max-file-line-count': [true, 1500],
  'member-access': false,
  'member-ordering': [
    true,
    {
      order: [
        'public-static-field',
        'protected-static-field',
        'private-static-field',
        'public-instance-field',
        'protected-instance-field',
        'private-instance-field',
        'public-static-method',
        'protected-static-method',
        'private-static-method',
        'public-constructor',
        'protected-constructor',
        'private-constructor',
        'public-instance-method',
        'protected-instance-method',
        'private-instance-method',
      ],
    },
  ],
  'new-parens': true,
  'no-arg': true,
  'no-boolean-literal-compare': true,
  'no-conditional-assignment': true,
  'no-construct': true,
  'no-debugger': true,
  'no-default-export': true,
  'no-duplicate-super': true,
  'no-duplicate-switch-case': true,
  'no-empty': false,
  'no-empty-interface': true,
  'no-eval': true,
  'no-for-in-array': true,
  'no-implicit-dependencies': [true, 'dev', ['~']],
  'no-inferrable-types': false,
  'no-inferred-empty-object-type': true,
  'no-irregular-whitespace': true,
  'no-invalid-template-strings': true,
  'no-misused-new': true,
  'no-non-null-assertion': true,
  'no-redundant-jsdoc': true,
  'no-return-await': true,
  'no-shadowed-variable': true,
  'no-sparse-arrays': true,
  'no-string-literal': true,
  'no-string-throw': true,
  'no-switch-case-fall-through': true,
  'no-this-assignment': [
    true,
    {
      'allow-destructuring': true,
    },
  ],
  'no-unnecessary-callback-wrapper': true,
  'no-unnecessary-initializer': true,
  'no-unnecessary-qualifier': true,
  'no-unsafe-finally': true,
  'no-unused-expression': true,
  'no-use-before-declare': false,
  'no-var-keyword': true,
  'number-literal-format': true,
  'object-literal-shorthand': true,
  'one-line': true,
  'one-variable-per-declaration': true,
  'only-arrow-functions': [true, 'allow-declarations', 'allow-named-functions'],
  'ordered-imports': [
    true,
    {
      'grouped-imports': true,
      'groups': ['^((?!css).)*$', 'css'],
    },
  ],
  'prefer-conditional-expression': [true, 'check-else-if'],
  'prefer-const': true,
  'prefer-for-of': true,
  'prefer-object-spread': true,
  'prefer-method-signature': true,
  'prefer-readonly': true,
  'prefer-switch': [
    true,
    {
      'min-cases': 3,
    },
  ],
  'prefer-template': true,
  'promise-function-async': true,
  'radix': true,
  'restrict-plus-operands': true,
  'switch-final-break': true,
  'triple-equals': true,
  'typedef': [true, 'call-signature', 'parameter', 'property-declaration'],
  'type-literal-delimiter': true,
  'unified-signatures': true,
  'use-default-type-parameter': true,
  'use-isnan': true,
  'variable-name': [true, 'ban-keywords', 'check-format', 'allow-pascal-case'],
};
